/*
 * login.java
 *
 * Created on __DATE__, __TIME__
 */

package com.jry.view.login;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.jry.action.LoginAction;
import com.jry.model.TpUser;
import com.jry.util.StringUtil;
import com.jry.util.sqlitepool.ConnectionFactory;
import com.jry.view.MainFrm;

/**
 *
 * @author __USER__
 */
public class login extends JFrame {
	private LoginAction loginAction = new LoginAction();

	/** Creates new form login */
	public login() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		logNameTxt = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jB_login = new javax.swing.JButton();
		jB_reset = new javax.swing.JButton();
		passwordTxt = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocationByPlatform(true);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 36));
		jLabel1.setText("\u8bbe\u5907\u6d4b\u8bd5\u5e73\u53f0");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jLabel2.setText("\u7528\u6237\u540d\uff1a");

		jLabel3.setText("   \u5bc6\u7801\uff1a");

		jB_login.setText("\u767b\u5f55");
		jB_login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jB_loginActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jB_reset.setText("\u91cd\u7f6e");
		jB_reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jB_resetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(172,
																		172,
																		172)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel3))
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						logNameTxt,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						297,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						passwordTxt)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(248,
																		248,
																		248)
																.addComponent(
																		jB_login)
																.addGap(100,
																		100,
																		100)
																.addComponent(
																		jB_reset))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(249,
																		249,
																		249)
																.addComponent(
																		jLabel1)))
								.addContainerGap(194, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(96, 96, 96)
								.addComponent(jLabel1)
								.addGap(99, 99, 99)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														logNameTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(55, 55, 55)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel3)
												.addComponent(
														passwordTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(50, 50, 50)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jB_reset)
												.addComponent(jB_login))
								.addContainerGap(111, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void jB_resetActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String userNameTxt = this.logNameTxt.getText();
		String passwordTxt = this.passwordTxt.getText();
		System.out.println("userNameTxt------:" + userNameTxt);
		System.out.println("passwordTxt------:" + passwordTxt);
		this.logNameTxt.setText("");
		this.passwordTxt.setText("");
	}

	private void jB_loginActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		// TODO add your handling code here:
		String userName = this.logNameTxt.getText();
		String password = new String(this.passwordTxt.getPassword());
		Connection conn = ConnectionFactory.gerSqliteFactory().getCon();
		if (StringUtil.isEmpty(userName)) {
			JOptionPane.showMessageDialog(null, "用户名不能为空！");
			return;
		}
		if (StringUtil.isEmpty(password)) {
			JOptionPane.showMessageDialog(null, "密码不能为空！");
			return;
		}

		TpUser tpUser = new TpUser();
		tpUser.setLogName(userName);
		tpUser.setPassword(password);
		boolean flag = loginAction.loginAction(conn, tpUser);
		conn.close();
		if (flag) {
			this.dispose();
			new MainFrm().setVisible(true);
			// JOptionPane.showMessageDialog(null, "登录成功");
		} else {
			JOptionPane.showMessageDialog(null, "用户名或密码错误！");
		}

	}

	/**
	 * 设置frame居中显示
	 */
	private void setFrameCenter(JFrame frame) {
		// ��ȡ���ڿ��
		int windowWidth = frame.getWidth();
		int windowHeight = frame.getHeight();
		Toolkit kit = Toolkit.getDefaultToolkit();
		Dimension screenSize = kit.getScreenSize();
		int screenWidth = screenSize.width;
		int screenHeight = screenSize.height;
		frame.setLocation(screenWidth / 2 - windowWidth / 2, screenHeight / 2
				- windowWidth / 2);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new login().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jB_login;
	private javax.swing.JButton jB_reset;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField logNameTxt;
	private javax.swing.JPasswordField passwordTxt;
	// End of variables declaration//GEN-END:variables

}